from BaseClasses import Item, ItemClassification

class AgainstTheStormItem(Item):
    game: str = "Against The Storm"

item_dict = {
    "Berries": (ItemClassification.progression, 1),
    "Eggs": (ItemClassification.progression, 1),
    "Insects": (ItemClassification.progression, 1),
    "Meat": (ItemClassification.progression, 1),
    "Mushrooms": (ItemClassification.progression, 1),
    "Roots": (ItemClassification.progression, 1),
    "Vegetables": (ItemClassification.progression, 1),
    "Biscuits": (ItemClassification.progression, 1),
    "Jerky": (ItemClassification.progression, 1),
    "Pickled Goods": (ItemClassification.progression, 1),
    "Pie": (ItemClassification.progression, 1),
    "Porridge": (ItemClassification.progression, 1),
    "Skewers": (ItemClassification.progression, 1),
    "Coats": (ItemClassification.progression, 1),
    "Bricks": (ItemClassification.progression, 1),
    "Fabric": (ItemClassification.progression, 1),
    "Planks": (ItemClassification.progression, 1),
    "Pipes": (ItemClassification.progression, 1),
    "Parts": (ItemClassification.useful, 1),
    "Wildfire Essence": (ItemClassification.useful, 1),
    "Ale": (ItemClassification.progression, 1),
    "Incense": (ItemClassification.progression, 1),
    "Scrolls": (ItemClassification.progression, 1),
    "Tea": (ItemClassification.progression, 1),
    "Training Gear": (ItemClassification.progression, 1),
    "Wine": (ItemClassification.progression, 1),
    "Clay": (ItemClassification.progression, 1),
    "Copper Ore": (ItemClassification.progression, 1),
    "Crystallized Dew": (ItemClassification.progression, 1),
    "Grain": (ItemClassification.progression, 1),
    "Herbs": (ItemClassification.progression, 1),
    "Leather": (ItemClassification.progression, 1),
    "Plant Fiber": (ItemClassification.progression, 1),
    "Reeds": (ItemClassification.progression, 1),
    "Resin": (ItemClassification.progression, 1),
    "Stone": (ItemClassification.progression, 1),
    "Barrels": (ItemClassification.progression, 1),
    "Copper Bars": (ItemClassification.progression, 1),
    "Flour": (ItemClassification.progression, 1),
    "Pigment": (ItemClassification.progression, 1),
    "Pottery": (ItemClassification.progression, 1),
    "Waterskins": (ItemClassification.progression, 1),
    "Amber": (ItemClassification.progression, 1),
    "Pack of Building Materials": (ItemClassification.progression, 1),
    "Pack of Crops": (ItemClassification.progression, 1),
    "Pack of Luxury Goods": (ItemClassification.progression, 1),
    "Pack of Provisions": (ItemClassification.progression, 1),
    "Pack of Trade Goods": (ItemClassification.progression, 1),
    "Ancient Tablet": (ItemClassification.useful, 1),
    "Coal": (ItemClassification.progression, 1),
    "Oil": (ItemClassification.progression, 1),
    "Purging Fire": (ItemClassification.progression, 1),
    "Sea Marrow": (ItemClassification.progression, 1),
    "Tools": (ItemClassification.progression, 1),
    "Filler": (ItemClassification.filler, 1),
}
