from BaseClasses import Location

class AgainstTheStormLocation(Location):
    game: str = "Against the Storm"

# How to interpret these logic definitions:
# To reach a location, you need at least one item from each string. For example:
# ["A,B,C", "D,E"] means (A or B or C) and (D or E)
location_dict = {
    "First Reputation through Resolve - Humans": ["Porridge,Biscuits,Pie,Coats", "Planks", "Bricks"],
    "First Reputation through Resolve - Beavers": ["Ale,Scrolls,Wine", "Planks", "Bricks", "Fabric"],
    "First Reputation through Resolve - Lizards": [],
    "First Reputation through Resolve - Harpies": [],
    "First Reputation through Resolve - Foxes": [],
    "50 Resolve - Humans": ["Porridge,Biscuits,Pie", "Coats", "Ale", "Incense", "Planks", "Fabric", "Bricks", "Purging Fire"],
    "50 Resolve - Beavers": ["Biscuits,Pickled Goods", "Coats", "Ale", "Scrolls", "Wine", "Planks", "Fabric", "Bricks", "Purging Fire"],
    "50 Resolve - Lizards": ["Jerky,Skewers,Pie,Pickled Goods", "Training Gear", "Incense", "Planks", "Fabric", "Bricks", "Purging Fire"],
    "50 Resolve - Harpies": ["Jerky,Biscuits,Pie", "Coats", "Scrolls", "Tea", "Planks", "Fabric", "Bricks", "Purging Fire"],
    "50 Resolve - Foxes": ["Porridge,Skewers,Pickled Goods", "Training Gear", "Wine", "Tea", "Planks", "Fabric", "Bricks", "Purging Fire"],
    "1st Reputation - Royal Woodlands": [],
    "10th Reputation - Royal Woodlands": ["Planks", "Bricks,Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools,Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "Victory - Royal Woodlands": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "1st Reputation - Coral Forest": [],
    "10th Reputation - Coral Forest": ["Planks", "Bricks,Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools,Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "Victory - Coral Forest": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "1st Reputation - The Marhslands": [],
    "10th Reputation - The Marhslands": ["Planks", "Bricks,Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools,Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "Victory - The Marhslands": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "1st Reputation - Scarlet Orchard": [],
    "10th Reputation - Scarlet Orchard": ["Planks", "Bricks,Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools,Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "Victory - Scarlet Orchard": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "1st Reputation - Cursed Royal Woodlands": [],
    "10th Reputation - Cursed Royal Woodlands": ["Planks", "Bricks,Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools,Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "Victory - Cursed Royal Woodlands": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "Trade - 10 Amber": ["Amber"],
    "Trade - 100 Amber": ["Amber", "Pack of Provisions", "Planks"],
    "Trade - 1000 Amber": ["Amber", "Pack of Provisions", "Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Pack of Building Materials,Pack of Crops,Pack of Luxury Goods,Pack of Trade Goods", "Purging Fire"],
    "Trade - 20 Packs of Building Materials": ["Pack of Building Materials"],
    "Trade - 20 Packs of Crops": ["Pack of Crops"],
    "Trade - 20 Packs of Provisions": ["Pack of Provisions"],
    "Trade - 20 Packs of Luxury Goods": ["Pack of Luxury Goods", "Planks"],
    "Trade - 20 Packs of Trade Goods": ["Pack of Trade Goods", "Planks"],
    "Trade - 200 Drizzle Water": ["Planks", "Pipes"],
    "Trade - 200 Clearance Water": ["Planks", "Pipes"],
    "Trade - 200 Storm Water": ["Planks", "Pipes"],
    "Completed Order - 1st Pack": [],
    "Completed Order - 2nd Pack": ["Berries,Eggs,Insects,Meat,Mushrooms,Roots,Vegetables"],
    "Completed Order - 3rd Pack": ["Berries,Eggs,Insects,Meat,Mushrooms,Roots,Vegetables", "Planks,Bricks,Fabric"],
    "Completed Order - 4th Pack": ["Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Planks", "Bricks,Fabric"],
    "Completed Order - 5th Pack": ["Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Planks", "Bricks,Fabric"],
    "Completed Order - 6th Pack": ["Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Planks", "Bricks,Fabric", "Purging Fire"],
    "Completed Order - 7th Pack": ["Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Planks", "Bricks,Fabric", "Purging Fire"],
    "Completed Order - 8th Pack": ["Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Planks", "Bricks", "Fabric", "Purging Fire"],
    "Completed Order - 9th Pack": ["Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Planks", "Bricks", "Fabric", "Amber,Tools", "Purging Fire"],
    "Upgraded Hearth - 1st Tier": [],
    "Upgraded Hearth - 2nd Tier": ["Planks"],
    "Upgraded Hearth - 3rd Tier": ["Planks", "Fabric", "Bricks"],
    "Complete a Dangerous Glade Event": ["Tools", "Oil,Coal,Sea Marrow", "Incense,Scrolls,Tea", "Planks"],
    "Complete a Forbidden Glade Event": ["Tools", "Oil,Coal,Sea Marrow", "Incense,Scrolls,Tea", "Planks", "Bricks,Fabric", "Purging Fire"],
    "Win with 30 Villagers in fully upgraded Housing - Humans": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire", "Pack of Building Materials", "Pack of Crops"],
    "Win with 30 Villagers in fully upgraded Housing - Beavers": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire", "Pack of Building Materials", "Amber,Pack of Trade Goods"],
    "Win with 30 Villagers in fully upgraded Housing - Lizards": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire", "Pack of Building Materials", "Jerky,Skewers"],
    "Win with 30 Villagers in fully upgraded Housing - Harpies": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire", "Pack of Building Materials", "Pigment"],
    "Win with 30 Villagers in fully upgraded Housing - Foxes": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire", "Pack of Building Materials", "Resin"],
}