from BaseClasses import Location

class AgainstTheStormLocation(Location):
    game: str = "Against the Storm"

# How to interpret these logic definitions:
# To reach a location, you need at least one item from each string. For example:
# ["A,B,C", "D,E"] means (A or B or C) and (D or E)
location_dict = {
    "First Reputation through Resolve - Humans": ["Porridge,Biscuits,Pie,Coats", "Planks", "Bricks"],
    "First Reputation through Resolve - Beavers": ["Ale,Scrolls,Wine", "Planks", "Bricks", "Fabric"],
    "First Reputation through Resolve - Lizards": [],
    "First Reputation through Resolve - Harpies": [],
    "First Reputation through Resolve - Foxes": [],
    "50 Resolve - Humans": ["Porridge,Biscuits,Pie", "Coats", "Ale", "Incense", "Planks", "Fabric", "Bricks", "Purging Fire"],
    "50 Resolve - Beavers": ["Biscuits,Pickled Goods", "Coats", "Ale", "Scrolls", "Wine", "Planks", "Fabric", "Bricks", "Purging Fire"],
    "50 Resolve - Lizards": ["Jerky,Skewers,Pie,Pickled Goods", "Training Gear", "Incense", "Planks", "Fabric", "Bricks", "Purging Fire"],
    "50 Resolve - Harpies": ["Jerky,Biscuits,Pie", "Coats", "Scrolls", "Tea", "Planks", "Fabric", "Bricks", "Purging Fire"],
    "50 Resolve - Foxes": ["Porridge,Skewers,Pickled Goods", "Training Gear", "Wine", "Tea", "Planks", "Fabric", "Bricks", "Purging Fire"],
    "1st Reputation - Royal Woodlands": [],
    "2nd Reputation - Royal Woodlands": ["Berries,Eggs,Insects,Meat,Mushrooms,Roots,Vegetables"],
    "3rd Reputation - Royal Woodlands": ["Berries,Eggs,Insects,Meat,Mushrooms,Roots,Vegetables"],
    "4th Reputation - Royal Woodlands": ["Planks,Bricks,Fabric", "Berries,Eggs,Insects,Meat,Mushrooms,Roots,Vegetables"],
    "5th Reputation - Royal Woodlands": ["Planks,Bricks,Fabric", "Berries,Eggs,Insects,Meat,Mushrooms,Roots,Vegetables", "Purging Fire"],
    "6th Reputation - Royal Woodlands": ["Planks,Bricks,Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Purging Fire"],
    "7th Reputation - Royal Woodlands": ["Planks,Bricks,Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Purging Fire"],
    "8th Reputation - Royal Woodlands": ["Planks", "Bricks,Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Purging Fire"],
    "9th Reputation - Royal Woodlands": ["Planks", "Bricks,Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Purging Fire"],
    "10th Reputation - Royal Woodlands": ["Planks", "Bricks,Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools,Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "11th Reputation - Royal Woodlands": ["Planks", "Bricks,Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools,Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "12th Reputation - Royal Woodlands": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools,Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "13th Reputation - Royal Woodlands": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools,Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "14th Reputation - Royal Woodlands": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "15th Reputation - Royal Woodlands": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "16th Reputation - Royal Woodlands": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "17th Reputation - Royal Woodlands": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "Victory - Royal Woodlands": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "1st Reputation - Coral Forest": [],
    "2nd Reputation - Coral Forest": ["Berries,Eggs,Insects,Meat,Mushrooms,Roots,Vegetables"],
    "3rd Reputation - Coral Forest": ["Berries,Eggs,Insects,Meat,Mushrooms,Roots,Vegetables"],
    "4th Reputation - Coral Forest": ["Planks,Bricks,Fabric", "Berries,Eggs,Insects,Meat,Mushrooms,Roots,Vegetables"],
    "5th Reputation - Coral Forest": ["Planks,Bricks,Fabric", "Berries,Eggs,Insects,Meat,Mushrooms,Roots,Vegetables", "Purging Fire"],
    "6th Reputation - Coral Forest": ["Planks,Bricks,Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Purging Fire"],
    "7th Reputation - Coral Forest": ["Planks,Bricks,Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Purging Fire"],
    "8th Reputation - Coral Forest": ["Planks", "Bricks,Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Purging Fire"],
    "9th Reputation - Coral Forest": ["Planks", "Bricks,Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Purging Fire"],
    "10th Reputation - Coral Forest": ["Planks", "Bricks,Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools,Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "11th Reputation - Coral Forest": ["Planks", "Bricks,Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools,Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "12th Reputation - Coral Forest": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools,Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "13th Reputation - Coral Forest": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools,Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "14th Reputation - Coral Forest": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "15th Reputation - Coral Forest": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "16th Reputation - Coral Forest": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "17th Reputation - Coral Forest": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "Victory - Coral Forest": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "1st Reputation - The Marshlands": [],
    "2nd Reputation - The Marshlands": ["Berries,Eggs,Insects,Meat,Mushrooms,Roots,Vegetables"],
    "3rd Reputation - The Marshlands": ["Berries,Eggs,Insects,Meat,Mushrooms,Roots,Vegetables"],
    "4th Reputation - The Marshlands": ["Planks,Bricks,Fabric", "Berries,Eggs,Insects,Meat,Mushrooms,Roots,Vegetables"],
    "5th Reputation - The Marshlands": ["Planks,Bricks,Fabric", "Berries,Eggs,Insects,Meat,Mushrooms,Roots,Vegetables", "Purging Fire"],
    "6th Reputation - The Marshlands": ["Planks,Bricks,Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Purging Fire"],
    "7th Reputation - The Marshlands": ["Planks,Bricks,Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Purging Fire"],
    "8th Reputation - The Marshlands": ["Planks", "Bricks,Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Purging Fire"],
    "9th Reputation - The Marshlands": ["Planks", "Bricks,Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Purging Fire"],
    "10th Reputation - The Marshlands": ["Planks", "Bricks,Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools,Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "11th Reputation - The Marshlands": ["Planks", "Bricks,Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools,Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "12th Reputation - The Marshlands": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools,Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "13th Reputation - The Marshlands": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools,Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "14th Reputation - The Marshlands": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "15th Reputation - The Marshlands": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "16th Reputation - The Marshlands": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "17th Reputation - The Marshlands": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "Victory - The Marshlands": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "1st Reputation - Scarlet Orchard": [],
    "2nd Reputation - Scarlet Orchard": ["Berries,Eggs,Insects,Meat,Mushrooms,Roots,Vegetables"],
    "3rd Reputation - Scarlet Orchard": ["Berries,Eggs,Insects,Meat,Mushrooms,Roots,Vegetables"],
    "4th Reputation - Scarlet Orchard": ["Planks,Bricks,Fabric", "Berries,Eggs,Insects,Meat,Mushrooms,Roots,Vegetables"],
    "5th Reputation - Scarlet Orchard": ["Planks,Bricks,Fabric", "Berries,Eggs,Insects,Meat,Mushrooms,Roots,Vegetables", "Purging Fire"],
    "6th Reputation - Scarlet Orchard": ["Planks,Bricks,Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Purging Fire"],
    "7th Reputation - Scarlet Orchard": ["Planks,Bricks,Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Purging Fire"],
    "8th Reputation - Scarlet Orchard": ["Planks", "Bricks,Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Purging Fire"],
    "9th Reputation - Scarlet Orchard": ["Planks", "Bricks,Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Purging Fire"],
    "10th Reputation - Scarlet Orchard": ["Planks", "Bricks,Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools,Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "11th Reputation - Scarlet Orchard": ["Planks", "Bricks,Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools,Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "12th Reputation - Scarlet Orchard": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools,Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "13th Reputation - Scarlet Orchard": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools,Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "14th Reputation - Scarlet Orchard": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "15th Reputation - Scarlet Orchard": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "16th Reputation - Scarlet Orchard": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "17th Reputation - Scarlet Orchard": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "Victory - Scarlet Orchard": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "1st Reputation - Cursed Royal Woodlands": [],
    "2nd Reputation - Cursed Royal Woodlands": ["Berries,Eggs,Insects,Meat,Mushrooms,Roots,Vegetables"],
    "3rd Reputation - Cursed Royal Woodlands": ["Berries,Eggs,Insects,Meat,Mushrooms,Roots,Vegetables"],
    "4th Reputation - Cursed Royal Woodlands": ["Planks,Bricks,Fabric", "Berries,Eggs,Insects,Meat,Mushrooms,Roots,Vegetables"],
    "5th Reputation - Cursed Royal Woodlands": ["Planks,Bricks,Fabric", "Berries,Eggs,Insects,Meat,Mushrooms,Roots,Vegetables", "Purging Fire"],
    "6th Reputation - Cursed Royal Woodlands": ["Planks,Bricks,Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Purging Fire"],
    "7th Reputation - Cursed Royal Woodlands": ["Planks,Bricks,Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Purging Fire"],
    "8th Reputation - Cursed Royal Woodlands": ["Planks", "Bricks,Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Purging Fire"],
    "9th Reputation - Cursed Royal Woodlands": ["Planks", "Bricks,Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Purging Fire"],
    "10th Reputation - Cursed Royal Woodlands": ["Planks", "Bricks,Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools,Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "11th Reputation - Cursed Royal Woodlands": ["Planks", "Bricks,Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools,Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "12th Reputation - Cursed Royal Woodlands": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools,Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "13th Reputation - Cursed Royal Woodlands": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools,Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "14th Reputation - Cursed Royal Woodlands": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "15th Reputation - Cursed Royal Woodlands": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "16th Reputation - Cursed Royal Woodlands": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "17th Reputation - Cursed Royal Woodlands": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "Victory - Cursed Royal Woodlands": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire"],
    "Trade - 10 Amber": ["Amber"],
    "Trade - 100 Amber": ["Amber", "Pack of Provisions", "Planks"],
    "Trade - 1000 Amber": ["Amber", "Pack of Provisions", "Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Pack of Building Materials,Pack of Crops,Pack of Luxury Goods,Pack of Trade Goods", "Purging Fire"],
    "Trade - 20 Pack of Building Materials": ["Pack of Building Materials"],
    "Trade - 20 Pack of Crops": ["Pack of Crops"],
    "Trade - 20 Pack of Provisions": ["Pack of Provisions"],
    "Trade - 20 Pack of Luxury Goods": ["Pack of Luxury Goods", "Planks"],
    "Trade - 20 Pack of Trade Goods": ["Pack of Trade Goods", "Planks"],
    "Trade - 200 Drizzle Water": ["Planks", "Pipes"],
    "Trade - 200 Clearance Water": ["Planks", "Pipes"],
    "Trade - 200 Storm Water": ["Planks", "Pipes"],
    "Reach level 1 standing with a neighbor": ["Amber", "Pack of Provisions"],
    "Reach level 2 standing with a neighbor": ["Amber", "Pack of Provisions", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods"],
    "Reach level 3 standing with a neighbor": ["Amber", "Planks,Fabric,Bricks", "Pack of Provisions", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Purging Fire"],
    "Reach level 4 standing with a neighbor": ["Amber", "Planks", "Fabric,Bricks", "Pack of Provisions", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Purging Fire", "Pack of Building Materials,Pack of Crops,Pack of Luxury Goods,Pack of Trade Goods"],
    "Reach level 5 standing with a neighbor": ["Amber", "Planks", "Fabric", "Bricks", "Pack of Provisions", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Purging Fire", "Pack of Building Materials,Pack of Crops,Pack of Luxury Goods,Pack of Trade Goods"],
    "Reach level 1 standing with ALL 4 neighbors": ["Amber", "Pack of Provisions", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods"],
    "Reach level 2 standing with ALL 4 neighbors": ["Amber", "Planks,Fabric,Bricks", "Pack of Provisions", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Purging Fire"],
    "Reach level 3 standing with ALL 4 neighbors": ["Amber", "Planks", "Fabric,Bricks", "Pack of Provisions", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Purging Fire", "Pack of Building Materials,Pack of Crops,Pack of Luxury Goods,Pack of Trade Goods"],
    "Reach level 4 standing with ALL 4 neighbors": ["Amber", "Planks", "Fabric", "Bricks", "Pack of Provisions", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Purging Fire", "Pack of Building Materials,Pack of Crops,Pack of Luxury Goods,Pack of Trade Goods"],
    "Reach level 5 standing with ALL 4 neighbors": ["Amber", "Planks", "Fabric", "Bricks", "Pack of Provisions", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Purging Fire", "Pack of Building Materials", "Pack of Crops", "Pack of Luxury Goods", "Pack of Trade Goods"],
    "Completed Order - 1st Pack": [],
    "Completed Order - 2nd Pack": ["Berries,Eggs,Insects,Meat,Mushrooms,Roots,Vegetables"],
    "Completed Order - 3rd Pack": ["Berries,Eggs,Insects,Meat,Mushrooms,Roots,Vegetables", "Planks,Bricks,Fabric"],
    "Completed Order - 4th Pack": ["Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Planks", "Bricks,Fabric"],
    "Completed Order - 5th Pack": ["Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Planks", "Bricks,Fabric"],
    "Completed Order - 6th Pack": ["Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Planks", "Bricks,Fabric", "Purging Fire"],
    "Completed Order - 7th Pack": ["Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Planks", "Bricks,Fabric", "Purging Fire"],
    "Completed Order - 8th Pack": ["Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Planks", "Bricks", "Fabric", "Purging Fire"],
    "Completed Order - 9th Pack": ["Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Planks", "Bricks", "Fabric", "Amber,Tools", "Purging Fire"],
    "Upgraded Hearth - 1st Tier": [],
    "Upgraded Hearth - 2nd Tier": ["Planks"],
    "Upgraded Hearth - 3rd Tier": ["Planks", "Fabric", "Bricks"],
    "Complete a Dangerous Glade Event": ["Tools", "Oil,Coal,Sea Marrow", "Incense,Scrolls,Tea", "Planks"],
    "Complete a Forbidden Glade Event": ["Tools", "Oil,Coal,Sea Marrow", "Incense,Scrolls,Tea", "Planks", "Bricks,Fabric", "Purging Fire"],
    "Have 30 Villagers in fully upgraded Housing - Humans": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire", "Pack of Building Materials", "Pack of Crops"],
    "Have 30 Villagers in fully upgraded Housing - Beavers": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire", "Pack of Building Materials", "Amber,Pack of Trade Goods"],
    "Have 30 Villagers in fully upgraded Housing - Lizards": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire", "Pack of Building Materials", "Jerky,Skewers"],
    "Have 30 Villagers in fully upgraded Housing - Harpies": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire", "Pack of Building Materials", "Pigment"],
    "Have 30 Villagers in fully upgraded Housing - Foxes": ["Planks", "Bricks", "Fabric", "Jerky,Porridge,Skewers,Biscuits,Pie,Pickled Goods", "Amber,Tools", "Ale,Training Gear,Incense,Scrolls,Wine,Tea", "Purging Fire", "Pack of Building Materials", "Resin"],
}